### ISSUE TITLE
Excess loop initialisation

### ISSUE THREAD

**Issue by marcfedorow** [timakrutoi/lab17#24]
https://github.com/timakrutoi/lab17/blob/70a36d9355ca9dd5fd5b9919d602868a6204edc0/matrix.h#L28-L34
Any loop initialisation takes some resources.
You can print your matrix by iterating through it as a linear array (just incert every `matrix.columns()` elements a string `"]\n["`).
It could be less readable but more efficient.
Please check the performance increase and post the results in the comment to this issue.

**Comment by marcfedorow** [comment]
Also I think this function should be placed in .ipp

**Comment by timakrutoi** [comment]
I made operator << that contain only one loop:
```c++
template<typename T>
std::ostream& operator<<(std::ostream& out, matrix<T>& matrix) {
	out << "[ ";
	for (int i = 0; i < matrix.rows() * matrix.columns(); i++) {
		if (i % matrix.columns() == 0 && i > 0) out << "]\n[ ";
		out << matrix.get(i / matrix.rows(), i / matrix.columns()) << " ";
	}
	out << "]" << std::endl;
	return out;
}
```
And did 5 tests using two functions with 500x50 matrices:

**First one with old function:**

1. Matrix 500x50
Time(millisecond): 2802

2. Matrix 500x50
Time(millisecond): 2651

3. Matrix 500x50
Time(millisecond): 2647

4. Matrix 500x50
Time(millisecond): 2631

5. Matrix 500x50
Time(millisecond): 2683

Mean is 2682.8 milliseconds

**Second, with new function:**

1. Matrix 500x50
Time(millisecond): 2630

2. Matrix 500x50
Time(millisecond): 2679

3. Matrix 500x50
Time(millisecond): 2636

4. Matrix 500x50
Time(millisecond): 2684

5. Matrix 500x50
Time(millisecond): 2679

Mean is 2661.6 milliseconds

As you can see, new function is faster, but there isnt much difference between this two

**Comment by marcfedorow** [comment]
There are few ways for further optimization:
```cpp
for (int i = 0; i < matrix.rows() * matrix.columns(); i++) {
```
should be rewrited as
```cpp
size_t bound = matrix.rows() * matrix.columns();
for (suze_t i = 0; i < bound; ++i) {
```
so you will calculate `matrix.rows() * matrix.columns()` only once.

Obviously `i / matrix.columns()` should be replaced with `i % matrix.columns()`.

.get() takes some resource too, so this is that case when the usage of `friend`-functions is meaningful:
```cpp
template<typename T>
friend std::ostream& operator<<(std::ostream& out, const matrix<T>& matrix) {
	T* data = *matrix.data;
	size_t bound = matrix.size_x * matrix.size_y;
	for (size_t i = 0; i < bound; i++) {
		if ((i % rows) == 0) out << i ? "]\n[ " : "[ ";
		out << *(data + i) << " ";
	}
	out << "]" << std::endl;
	return out;
}
```
This could give some performance increase while we do not check bounds with every `.get()` call.
Due to `matrix` parameter is `const` we do not mind about `operator<<` can break something.

Try to test it with 1x10000 and 10000x1 matrices (compare old, your new and this versions).
While testing do enough experiments (it seems that 20 ms delta is less than statistical uncertainty on five tests).
Print operations could take too much time so while testing you can replace them with any simple operation (make sure this operations are not ignored while optimization). Copmare results with different levels of optimization (-O0 to -O3).

**Comment by marcfedorow** [comment]
Well probably it is better to test the performance delta of a loop dispose on #27.
